### ISSUE TITLE
Version 3.0 ?

### ISSUE THREAD

**Issue by ohomer** [koajs/static#72] opened 2016-01-20 20:47 UTC
I've gone through and butchered the source code, making it behave as I think it should. The result is here:

[koa-better-static](https://github.com/ohomer/koa-better-static)

There's a few breaking changes, but I think it's a clear improvement for the vast majority of use cases. 
If you guys are amenable to it, I'd encourage to pull my version in as koa-static v3.

**Comment by niftylettuce** [comment] 2016-01-20 21:03
@ohomer hey have you looked at something like this? (using `koa-mount`)

```js
app.use(mount('/scripts', convert(serveStatic(
  path.join(__dirname, 'scripts'),
  config.serveStatic
))));
```

I can access a file that's in this `scripts/` directory by doing `curl http://localhost:3000/editor.js` and also by doing `curl http://localhost:3000/scripts/editor.js`.  For some reason it's allowing both paths.

**Comment by RHavar** [comment] 2016-01-20 22:12
Really? That's for koa-better-static?  I've been trying, and can't reproduce that problem at all :(

Are you sure it's not getting served by any other middleware or something?

**Comment by ohomer** [comment] 2016-01-20 23:36
I wrote some tests with koa-mount  (koa 1 though), and haven't been able to find any issue. I haven't looked much into koa 2 to try it.

**Comment by coderhaoxin** [comment] 2016-01-21 01:26
@ohomer If you are bother with https://github.com/koajs/static/pull/70, I think @tejasmanohar will send a PR?

I just take a look at https://github.com/ohomer/koa-better-static,

> Supports If-Modified-Since header for cache/performance

This can be done by https://github.com/koajs/conditional-get, I'll add this to `Readme.md`

You port the whole `koa-send`? Remove `root` concept?

I'm `-1` on this.

**Comment by ohomer** [comment] 2016-01-21 02:10
It fixes #70 but that's not just a side detail. The main point was to cleanup the code and have more reasonable defaults, aim for higher performance even though they cause a small amount of breaks.

`conditional-get` is nice, but it's not really the best spot to do it. For one, it's inefficient (the static middleware has exactly what it needs to know to not attempt to serve the file in the first place) and it's probably in the wrong spot. You might want to only use the freshness stuff for static content, you don't want to put it on the global middleware. 

I think I have a rather typical use-case (sending static files), and koa-better-static is giving me a sustained ~200 req/s faster than even with an optimized koa-static  (turning gzip, index off and and using conditional-get). Of course your mileage might vary, but I don't see any convincing reason to *not* use it.

**Comment by niftylettuce** [comment] 2016-01-21 03:36
@ohomer actually your `koa-better-static` resolves my issue from https://github.com/koajs/static/issues/72#issuecomment-173357953

Can you give me insight as to what's changed in the codebase to cause this? (and to make yours work and theirs not)

Stumped

**Comment by ohomer** [comment] 2016-01-21 15:00
@niftylettuce Ah, yeah, I fixed all that up by moving it from `send` into the [main middleware file](https://github.com/ohomer/koa-better-static/blob/master/index.js) and so now the send layer directly takes the canonicalize filepath. There was a weird impedance mismatch between koa-send and koa-static so I found the cleanest approach was just to mash them together, and clean it up

There's still a few more performance tweaks I want to make, but it's become pretty stable as a drop in replacement. I'm using it in production, so I intend on maintaining it, unless koa-static wants to adopt it (which I think would be ideal)

**Comment by fritx** [comment] 2016-01-24 15:34
How to use koa-static with koa v2?

**Comment by coderhaoxin** [comment] 2016-01-24 15:37
@fritx At this moment, try https://github.com/koajs/convert

**Comment by fritx** [comment] 2016-01-25 02:29
nice @coderhaoxin that must be what i'm looking for :+1:

**Comment by dtothefp** [comment] 2016-02-05 20:06
@coderhaoxin tried using both `serve-better-static` and `static` wrapped in `convert` with Koa 2 can keep getting this Bluebird warning. Is this expected?

```js
import serve from 'koa-better-static';

const app = new Koa();
app.use(convert(serve(buildDir)));
```

```
Warning: a promise was created in a handler but was not returned from it
    at /Users/davidfox-powell/dev/secretary-of-state/lib/server/index.js:37:99
    at index.js:22:9
    at dispatch (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-compose/index.js:41:32)
    at next (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-compose/index.js:42:18)
    at createGenerator (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-convert/index.js:24:16)
    at [object Generator].next (native)
    at Object.serve (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-better-static/index.js:71:5)
    at [object Generator].next (native)
    at onFulfilled (/Users/davidfox-powell/dev/secretary-of-state/node_modules/co/index.js:65:19)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at next (/Users/davidfox-powell/dev/secretary-of-state/node_modules/co/index.js:100:51)
    at onFulfilled (/Users/davidfox-powell/dev/secretary-of-state/node_modules/co/index.js:69:7)
    at /Users/davidfox-powell/dev/secretary-of-state/node_modules/co/index.js:54:5
From previous event:
    at Object.co (/Users/davidfox-powell/dev/secretary-of-state/node_modules/co/index.js:50:10)
    at converted (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-convert/index.js:17:15)
    at dispatch (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-compose/index.js:41:32)
    at /Users/davidfox-powell/dev/secretary-of-state/node_modules/koa-compose/index.js:34:12
    at Server.<anonymous> (/Users/davidfox-powell/dev/secretary-of-state/node_modules/koa/lib/application.js:126:7)
    at emitTwo (events.js:100:13)
    at Server.emit (events.js:185:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:537:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
```

**Comment by coderhaoxin** [comment] 2016-02-06 14:01
@dtothefp https://github.com/koajs/send/issues/47

**Comment by tejasmanohar** [comment] 2016-02-06 19:16
so many issues opened about this :\ - should we add it to the @koajs readme?

**Comment by dtothefp** [comment] 2016-02-07 00:43
@tejasmanohar seems weird this module has not been upated for `2.x`, imagining this wouldn't be an issue because `co` is not involved at that point. Is there a good module for this functionality we can use without `convert`?

**Comment by tejasmanohar** [comment] 2016-02-07 01:18
2.x isn't stable and it won't be released for a long time. use `koa-convert`

**Comment by coderhaoxin** [comment] 2016-02-07 09:41
> so many issues opened about this :\ - should we add it to the koajs/koa readme?

@tejasmanohar you mean bluebird warning? It's not koa's stuff IMO o_O

For `koa-convert`, +1 to koa's Readme >_<.

**Comment by tejasmanohar** [comment] 2016-02-07 18:14
yeah it's not koa stuff but seems to cause so many issues :P

**Comment by coderhaoxin** [comment] 2017-02-26 14:44
@ohomer current master branch is `koa-static@3.0.0` for `koa@2`.

Since this issue contains some more outdated topics, just closed it. :)

Feel free to open a new issue for your advice!

**Closed by coderhaoxin** 2017-02-26 14:44 UTC
Labels: question
